<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-07T13:12:44 IST" name="Default suite" finished-at="2025-05-07T13:12:56 IST" duration-ms="12432">
    <groups>
    </groups>
    <test started-at="2025-05-07T13:12:44 IST" name="Default test" finished-at="2025-05-07T13:12:56 IST" duration-ms="12432">
      <class name="Home_Page_Menu.Home_Menu_Body">
        <test-method is-config="true" signature="setup()[pri:0, instance:Home_Page_Menu.Home_Menu_Body@20d525]" started-at="2025-05-07T13:12:44 IST" name="setup" finished-at="2025-05-07T13:12:46 IST" duration-ms="2175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="URl_Call()[pri:0, instance:Home_Page_Menu.Home_Menu_Body@20d525]" started-at="2025-05-07T13:12:46 IST" name="URl_Call" finished-at="2025-05-07T13:12:47 IST" duration-ms="1405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- URl_Call -->
        <test-method signature="Header()[pri:10, instance:Home_Page_Menu.Home_Menu_Body@20d525]" started-at="2025-05-07T13:12:47 IST" name="Header" finished-at="2025-05-07T13:12:47 IST" duration-ms="263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Header -->
        <test-method is-config="true" signature="URl_Call()[pri:0, instance:Home_Page_Menu.Home_Menu_Body@20d525]" started-at="2025-05-07T13:12:48 IST" name="URl_Call" finished-at="2025-05-07T13:12:48 IST" duration-ms="549" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- URl_Call -->
        <test-method signature="Header_Freeze()[pri:11, instance:Home_Page_Menu.Home_Menu_Body@20d525]" started-at="2025-05-07T13:12:48 IST" name="Header_Freeze" finished-at="2025-05-07T13:12:51 IST" duration-ms="3291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Header_Freeze -->
        <test-method is-config="true" signature="URl_Call()[pri:0, instance:Home_Page_Menu.Home_Menu_Body@20d525]" started-at="2025-05-07T13:12:51 IST" name="URl_Call" finished-at="2025-05-07T13:12:52 IST" duration-ms="606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- URl_Call -->
        <test-method signature="Footer()[pri:12, instance:Home_Page_Menu.Home_Menu_Body@20d525]" started-at="2025-05-07T13:12:52 IST" name="Footer" finished-at="2025-05-07T13:12:56 IST" duration-ms="3783" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Base_Setup.Base_Code_Configuration.AssertFail(Base_Code_Configuration.java:327)
at Home_Page_Menu.Home_Menu_Body.Footer(Home_Menu_Body.java:260)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Footer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Home_Page_Menu.Home_Menu_Body@20d525]" started-at="2025-05-07T13:12:56 IST" name="tearDown" finished-at="2025-05-07T13:12:56 IST" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Home_Page_Menu.Home_Menu_Body -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
